# Знакомство с библиотекой Numpy

In [40]:
import numpy as np

In [4]:
x = np.array([1, 2, 3, 4])

In [5]:
x

array([1, 2, 3, 4])

In [6]:
x.dtype

dtype('int32')

In [8]:
x = np.array([1, 2, 3, 4], dtype = np.int64)
x.dtype

dtype('int64')

In [9]:
x.shape

(4,)

In [11]:
m = np.array([[2, 3, 4], [5, 6, 7]])
m

array([[2, 3, 4],
       [5, 6, 7]])

In [12]:
m.shape

(2, 3)

In [14]:
print (np.zeros(5))
print (np.ones(5))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [15]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [16]:
np.random.random((2, 3))

array([[0.88904734, 0.38571387, 0.445175  ],
       [0.88055592, 0.19361246, 0.28872369]])

In [18]:
y = np.array([[1, 3, 4, 4], [2, 3, 4, 56]])
y

array([[ 1,  3,  4,  4],
       [ 2,  3,  4, 56]])

In [21]:
print (y[1, 3])
print (y[:, :3])
print (y[:, 3:])

56
[[1 3 4]
 [2 3 4]]
[[ 4]
 [56]]


In [23]:
print (y > 2)
print (y[y>2])

[[False  True  True  True]
 [False  True  True  True]]
[ 3  4  4  3  4 56]


In [24]:
b = np.array([[1, 3, 4, 4, 5], [2, 3, 4, 56, 5]])
b.shape

(2, 5)

In [25]:
b.flatten()

array([ 1,  3,  4,  4,  5,  2,  3,  4, 56,  5])

In [26]:
b.T

array([[ 1,  2],
       [ 3,  3],
       [ 4,  4],
       [ 4, 56],
       [ 5,  5]])

In [29]:
# размер новой равен размеру старой, reshape не меняет сам массив
b.reshape((10, 1))

array([[ 1],
       [ 3],
       [ 4],
       [ 4],
       [ 5],
       [ 2],
       [ 3],
       [ 4],
       [56],
       [ 5]])

In [31]:
# размер новой равен размеру старой, resize меняет сам массив
b.resize((10, 1))
b

array([[ 1],
       [ 3],
       [ 4],
       [ 4],
       [ 5],
       [ 2],
       [ 3],
       [ 4],
       [56],
       [ 5]])

In [32]:
v = np.array([9, 10])
w = np.array([11, 12])

In [33]:
v + w

array([20, 22])

In [35]:
np.add(v, w)

array([20, 22])

In [36]:
v*w

array([ 99, 120])

In [38]:
np.multiply(v, w)

array([ 99, 120])

In [39]:
np.dot(v, w)

219